### ISSUE TITLE
package dependency error when installing temporalite

### ISSUE THREAD

**Issue by larrymjordan** [DataDog/temporalite#18] opened 2021-12-01 17:07 UTC
## Expected Behavior
the `go install github.com/DataDog/temporalite/cmd/temporalite@latest` command should produce the binary for temporalite without any errors.

## Actual Behavior
Getting this error when trying to install temporalite as suggested in [Getting started](https://github.com/DataDog/temporalite#getting-started)  page

```
../pkg/mod/go.temporal.io/server@v1.13.1-0.20211115193149-58af5da4d614/common/metrics/config.go:31:2: ambiguous import: found package github.com/cactus/go-statsd-client/statsd in multiple modules:
	github.com/cactus/go-statsd-client v3.1.1+incompatible (~/go/pkg/mod/github.com/cactus/go-statsd-client@v3.1.1+incompatible/statsd)
	github.com/cactus/go-statsd-client/statsd v0.0.0-20200423205355-cb0885a1018c (~/go/pkg/mod/github.com/cactus/go-statsd-client/statsd@v0.0.0-20200423205355-cb0885a1018c)
```

## Steps to Reproduce the Problem
1. Execute this command `go install github.com/DataDog/temporalite/cmd/temporalite@latest` 

## Specifications
- Version: go1.16.3 
- Platform:  darwin/amd64

## Potential Solution
Add this statement to **go.mod** file solved the problem on my side:

`replace github.com/cactus/go-statsd-client => github.com/cactus/go-statsd-client v3.2.1+incompatible`

**Comment by cretz** [comment] 2021-12-01 17:24
https://github.com/uber-go/tally/pull/171 was merged to hopefully solve this problem. _Hopefully_ this `replace` will not be needed soon. But in the meantime, `go.mod` on the Temporal side does have this `replace` and since `replace`s aren't transitive, it would have to be applied here too.

**Comment by larrymjordan** [comment] 2021-12-02 15:00
@cretz  seems like updating go version to 1.17.3 solves the issue too without using `replace`. Credits to @SirUela and @amartine59

**Comment by jlegrone** [comment] 2021-12-13 09:36
Yep I think this is because `go mod tidy -compat=1.17` was used, which removes checksums needed for Go 1.16. I haven't verified yet but #20 may have fixed this.

Note that Temporalite compatibility with previous Go releases is currently on a best-effort basis and may break at any time due to internal usage of new features or the same in one of our dependencies. For example we may start making use of [T.Setenv](https://pkg.go.dev/testing#T.Setenv) to simplify testing CLI tools like `tctl` that read in connection options from the environment.

**Comment by cretz** [comment] 2021-12-13 17:14
@jlegrone - I have just merged https://github.com/temporalio/temporal/pull/2296 which will alleviate this statsd issue when y'all get there.

**Comment by jlegrone** [comment] 2022-04-04 23:13
Temporal upstream just [started requiring Go 1.18](https://github.com/temporalio/temporal/pull/2626), and Temporalite will need to adopt the same requirements.

Since this issue appears to only be reproducible on Go 1.16, I'm going to resolve it. Please feel free to file a new issue if similar problems crop up on Go 1.18+!

**Closed by jlegrone** 2022-04-04 23:13 UTC

**Comment by jackielii** [comment] 2022-05-22 19:48
This is happening again on [latest](https://github.com/DataDog/temporalite/blob/0e5171390aad62f0483d24afa48fd4208431f039/go.mod):

```
go get github.com/DataDog/temporalite/cmd/temporalite@latest
Found existing alias for "go get". You should use: "gog"
go: downloading github.com/urfave/cli/v2 v2.6.0
go: downloading github.com/temporalio/ui-server v0.13.1
go: downloading github.com/urfave/cli v1.22.5
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading github.com/labstack/echo-contrib v0.12.0
go: downloading github.com/coreos/go-oidc/v3 v3.1.0
go: downloading github.com/cactus/go-statsd-client v3.2.1+incompatible
github.com/DataDog/temporalite/cmd/temporalite imports
        github.com/DataDog/temporalite/internal/liteconfig imports
        go.temporal.io/server/common/metrics imports
        github.com/cactus/go-statsd-client/statsd: ambiguous import: found package github.com/cactus/go-statsd-client/statsd in multiple modules:
        github.com/cactus/go-statsd-client v3.1.1+incompatible (/Users/jackieli/go/pkg/mod/github.com/cactus/go-statsd-client@v3.1.1+incompatible/statsd)
        github.com/cactus/go-statsd-client/statsd v0.0.0-20200423205355-cb0885a1018c (/Users/jackieli/go/pkg/mod/github.com/cactus/go-statsd-client/statsd@v0.0.0-20200423205355-cb0885a1018c)
```

**Comment by jackielii** [comment] 2022-05-22 21:06
hmmm. Just tried creating a new project and import the `github.com/DataDog/temporalite/temporaltest` package. It all worked. Same command in existing project just doesn't:

```
../../../go/pkg/mod/go.temporal.io/server@v1.16.2/common/metrics/config.go:31:2: ambiguous import: found package github.com/cactus/go-statsd-client/statsd in multiple modules:
        github.com/cactus/go-statsd-client v3.1.1+incompatible (/Users/jackieli/go/pkg/mod/github.com/cactus/go-statsd-client@v3.1.1+incompatible/statsd)
        github.com/cactus/go-statsd-client/statsd v0.0.0-20200423205355-cb0885a1018c (/Users/jackieli/go/pkg/mod/github.com/cactus/go-statsd-client/statsd@v0.0.0-20200423205355-cb0885a1018c)
```

**Comment by jackielii** [comment] 2022-05-22 21:42
somehow I needed the following replacement directives:


```
replace github.com/cactus/go-statsd-client => github.com/cactus/go-statsd-client v0.0.0-20200423205355-cb0885a1018c

replace github.com/apache/thrift => github.com/apache/thrift v0.0.0-20161221203622-b2a4d4ae21c7 // indirect
```

**Comment by kennedyjustin** [comment] 2022-05-23 14:48
With `go get -u github.com/DataDog/temporalite` am getting:


```
github.com/DataDog/temporalite imports
        github.com/DataDog/temporalite/internal/liteconfig imports
        go.temporal.io/server/common/metrics imports
        github.com/cactus/go-statsd-client/statsd: ambiguous import: found package github.com/cactus/go-statsd-client/statsd in multiple modules:
        github.com/cactus/go-statsd-client v3.1.1+incompatible (/Users/justin/go/pkg/mod/github.com/cactus/go-statsd-client@v3.1.1+incompatible/statsd)
        github.com/cactus/go-statsd-client/statsd v0.0.0-20200423205355-cb0885a1018c (/Users/justin/go/pkg/mod/github.com/cactus/go-statsd-client/statsd@v0.0.0-20200423205355-cb0885a1018c)
github.com/DataDog/temporalite imports
        github.com/DataDog/temporalite/internal/liteconfig imports
        go.temporal.io/server/common/metrics imports
        go.opentelemetry.io/otel/metric/metrictest: cannot find module providing package go.opentelemetry.io/otel/metric/metrictest
github.com/DataDog/temporalite imports
        github.com/DataDog/temporalite/internal/liteconfig imports
        go.temporal.io/server/common/metrics imports
        go.opentelemetry.io/otel/metric/sdkapi: cannot find module providing package go.opentelemetry.io/otel/metric/sdkapi
```

```
go version go1.18.1 darwin/amd64
```

**Comment by jackielii** [comment] 2022-08-24 19:56
Can we re-open this issue?

as of today, `go get -u -v github.com/temporalio/temporalite/temporaltest` still shows error:


```
$ go get -u -v github.com/temporalio/temporalite/temporaltest
Found existing alias for "go get". You should use: "gog"
github.com/temporalio/temporalite/temporaltest imports
        github.com/temporalio/temporalite imports
        github.com/temporalio/temporalite/internal/liteconfig imports
        go.temporal.io/server/common/metrics imports
        github.com/cactus/go-statsd-client/statsd: ambiguous import: found package github.com/cactus/go-statsd-client/statsd in multiple modules:
        github.com/cactus/go-statsd-client v3.1.1+incompatible (/Users/jackieli/go/pkg/mod/github.com/cactus/go-statsd-client@v3.1.1+incompatible/statsd)
        github.com/cactus/go-statsd-client/statsd v0.0.0-20200423205355-cb0885a1018c (/Users/jackieli/go/pkg/mod/github.com/cactus/go-statsd-client/statsd@v0.0.0-20200423205355-cb0885a1018c)
```

using `go 1.19` in go.mod
